# Generated by Django 3.0.2 on 2020-03-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0003_auto_20200301_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortal',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('urls', models.TextField()),
                ('data', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Trendingtopics',
        ),
    ]
