# Generated by Django 3.0.2 on 2020-03-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0005_auto_20200303_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportal',
            name='sentiment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
